import { Injectable } from '@nestjs/common';
import { City } from './city.interface';

@Injectable()
export class CitiesService {
  private readonly cities: City[] = [
    {
      id: 'santiago',
      name: 'Santiago',
      region: 'Región Metropolitana',
      province: 'Santiago',
      population: 6310000,
      foundedYear: 1541,
      areaKm2: 641,
      coordinates: { latitude: -33.4489, longitude: -70.6693 },
      climate: 'Mediterráneo con inviernos lluviosos',
      economicActivity: 'Servicios financieros, comercio y tecnología',
      highlights: [
        'Capital de Chile y centro político-administrativo',
        'Costanera Center y barrio financiero de Tobalaba',
        'Cerro San Cristóbal y Parque Metropolitano',
      ],
      notableFacts: [
        'Concentra cerca del 40% del PIB nacional',
        'Sede de la Moneda, Congreso Nacional y principales ministerios',
        'Principal hub de startups y fintech de Latinoamérica',
      ],
      unescoSite: false,
    },
    {
      id: 'valparaiso',
      name: 'Valparaíso',
      region: 'Región de Valparaíso',
      province: 'Valparaíso',
      population: 296655,
      foundedYear: 1536,
      areaKm2: 402,
      coordinates: { latitude: -33.0472, longitude: -71.6127 },
      climate: 'Mediterráneo costero',
      economicActivity: 'Puerto, logística, turismo y cultura',
      highlights: [
        'Puerto principal histórico del Pacífico sur',
        'Ascensores patrimoniales y cerros pintados',
        'Casa de Pablo Neruda en La Sebastiana',
      ],
      notableFacts: [
        'Patrimonio de la Humanidad UNESCO desde 2003',
        'Capital cultural alternativa con festival de arte urbano',
        'Congreso Nacional se trasladó aquí en parte del año',
      ],
      unescoSite: true,
    },
    {
      id: 'vina-del-mar',
      name: 'Viña del Mar',
      region: 'Región de Valparaíso',
      province: 'Valparaíso',
      population: 334248,
      foundedYear: 1874,
      areaKm2: 122,
      coordinates: { latitude: -33.0153, longitude: -71.5506 },
      climate: 'Mediterráneo oceánico',
      economicActivity: 'Turismo, comercio y servicios',
      highlights: [
        'Ciudad Jardín y Reloj de Flores',
        'Festival Internacional de la Canción de Viña del Mar',
        'Playas de Reñaca y Concón cercanas',
      ],
      notableFacts: [
        'Principal destino balneario del centro de Chile',
        'Sede del Casino Municipal histórico',
        'Alta densidad hotelera y gastronómica',
      ],
      unescoSite: false,
    },
    {
      id: 'concepcion',
      name: 'Concepción',
      region: 'Región del Biobío',
      province: 'Concepción',
      population: 115528,
      foundedYear: 1550,
      areaKm2: 222,
      coordinates: { latitude: -36.8201, longitude: -73.0444 },
      climate: 'Templado oceánico',
      economicActivity: 'Industria forestal, pesca y educación superior',
      highlights: [
        'Universidad de Concepción y su arquitectura emblemática',
        'Península de Hualpén y desembocadura del Biobío',
        'Centro de innovación del sur de Chile',
      ],
      notableFacts: [
        'Segunda aglomeración urbana del país (Gran Concepción)',
        'Histórica capital industrial y portuaria del sur',
        'Epicentro del movimiento estudiantil chileno moderno',
      ],
      unescoSite: false,
    },
    {
      id: 'la-serena',
      name: 'La Serena',
      region: 'Región de Coquimbo',
      province: 'Elqui',
      population: 221054,
      foundedYear: 1544,
      areaKm2: 1892,
      coordinates: { latitude: -29.9027, longitude: -71.2519 },
      climate: 'Desértico costero',
      economicActivity: 'Turismo astronómico, agricultura y minería',
      highlights: [
        'Avenida del Mar y faro Monumental',
        'Proximidad al Valle del Elqui y observatorios',
        'Arquitectura neocolonial en el centro histórico',
      ],
      notableFacts: [
        'Segunda ciudad más antigua de Chile',
        'Puerta de entrada al cinturón astronómico mundial',
        'Alta radiación solar, ideal para observación nocturna',
      ],
      unescoSite: false,
    },
    {
      id: 'antofagasta',
      name: 'Antofagasta',
      region: 'Región de Antofagasta',
      province: 'Antofagasta',
      population: 425725,
      foundedYear: 1870,
      areaKm2: 3036,
      coordinates: { latitude: -23.6509, longitude: -70.3975 },
      climate: 'Desértico litoral',
      economicActivity: 'Minería del cobre, logística portuaria y energía',
      highlights: [
        'Muelle Salitrero histórico',
        'La Portada, formación rocosa en el Pacífico',
        'Hub logístico del norte grande minero',
      ],
      notableFacts: [
        'Concentra actividad vinculada a la Mina Escondida',
        'Puerto clave para exportación de concentrados de cobre',
        'Una de las ciudades con mayor crecimiento urbano reciente',
      ],
      unescoSite: false,
    },
    {
      id: 'iquique',
      name: 'Iquique',
      region: 'Región de Tarapacá',
      province: 'Iquique',
      population: 223463,
      foundedYear: 1585,
      areaKm2: 2835,
      coordinates: { latitude: -20.2307, longitude: -70.1357 },
      climate: 'Desértico costero',
      economicActivity: 'Comercio fronterizo, pesca y turismo',
      highlights: [
        'Baquedano Street y arquitectura salitrera',
        'Zona Franca de Iquique (ZOFRI)',
        'Playa Cavancha y deportes acuáticos',
      ],
      notableFacts: [
        'Principal ciudad del norte grande chileno',
        'Histórico centro del salitre en el siglo XIX',
        'Puerta comercial con Perú y Bolivia',
      ],
      unescoSite: false,
    },
    {
      id: 'temuco',
      name: 'Temuco',
      region: 'Región de La Araucanía',
      province: 'Cautín',
      population: 282415,
      foundedYear: 1881,
      areaKm2: 464,
      coordinates: { latitude: -38.7359, longitude: -72.5904 },
      climate: 'Templado lluvioso',
      economicActivity: 'Agroindustria, servicios y turismo mapuche',
      highlights: [
        'Mercado Municipal y gastronomía local',
        'Parque Nacional Conguillío cercano',
        'Patrimonio mapuche y ferias artesanales',
      ],
      notableFacts: [
        'Capital de La Araucanía y corazón del pueblo mapuche',
        'Centro de distribución agropecuaria del sur',
        'Entrada a volcanes Llaima y Sierra Nevada',
      ],
      unescoSite: false,
    },
    {
      id: 'puerto-montt',
      name: 'Puerto Montt',
      region: 'Región de Los Lagos',
      province: 'Llanquihue',
      population: 269398,
      foundedYear: 1853,
      areaKm2: 1673,
      coordinates: { latitude: -41.4693, longitude: -72.9424 },
      climate: 'Oceánico templado lluvioso',
      economicActivity: 'Salmonicultura, turismo y logística patagónica',
      highlights: [
        'Angelmo y feria de mariscos',
        'Navegación hacia Chiloé y fiordos',
        'Vista al volcán Calbuco',
      ],
      notableFacts: [
        'Capital de Los Lagos y puerta a la Patagonia norte',
        'Epicentro mundial de la industria del salmón',
        'Terminal de cruceros y ferries hacia el sur',
      ],
      unescoSite: false,
    },
    {
      id: 'punta-arenas',
      name: 'Punta Arenas',
      region: 'Región de Magallanes y Antártica Chilena',
      province: 'Magallanes',
      population: 149894,
      foundedYear: 1848,
      areaKm2: 10173,
      coordinates: { latitude: -53.1638, longitude: -70.9171 },
      climate: 'Subpolar oceánico',
      economicActivity: 'Energía, turismo antártico y logística',
      highlights: [
        'Costanera del Estrecho de Magallanes',
        'Cementerio Municipal y palacios históricos',
        'Expediciones hacia la Antártica',
      ],
      notableFacts: [
        'Ciudad más austral continental del mundo',
        'Histórico puerto ovino y extractivista',
        'Base de apoyo logístico para la Antártica chilena',
      ],
      unescoSite: false,
    },
    {
      id: 'arica',
      name: 'Arica',
      region: 'Región de Arica y Parinacota',
      province: 'Arica',
      population: 221054,
      foundedYear: 1541,
      areaKm2: 4799,
      coordinates: { latitude: -18.4783, longitude: -70.3126 },
      climate: 'Desértico tropical',
      economicActivity: 'Comercio fronterizo, turismo y servicios',
      highlights: [
        'Morro de Arica y museo histórico',
        'Playa Chinchorro y surf todo el año',
        'Termas de Lluta y valles preandinos',
      ],
      notableFacts: [
        'Ciudad más septentrional de Chile',
        'Clima estable con lluvias casi nulas',
        'Terminal clave del corredor bioceánico',
      ],
      unescoSite: false,
    },
    {
      id: 'castro',
      name: 'Castro',
      region: 'Región de Los Lagos',
      province: 'Chiloé',
      population: 47621,
      foundedYear: 1567,
      areaKm2: 427,
      coordinates: { latitude: -42.4827, longitude: -73.7615 },
      climate: 'Oceánico húmedo',
      economicActivity: 'Turismo cultural, pesca artesanal y artesanía',
      highlights: [
        'Iglesias de madera de Chiloé',
        'Palafitos sobre el borde costero',
        'Curanto y gastronomía isleña',
      ],
      notableFacts: [
        'Capital de la provincia de Chiloé',
        'Iglesias declaradas Patrimonio UNESCO en la isla',
        'Fuerte identidad cultural chilota y mitología local',
      ],
      unescoSite: true,
    },
  ];

  findAll(): City[] {
    return this.cities;
  }
}
